### ISSUE TITLE
de.pdark.decentxml.XMLParseException when I input japanese text in xml

### ISSUE THREAD

**Issue by hanggao121** [adobe/aem-eclipse-developer-tools#30]
I write japanese character in xml node,then occur exception.
Log:
de.pdark.decentxml.XMLParseException: Line 8, column 29: Missing end quote (") of attribute: "\n        sling:messa..."
    at org.apache.sling.ide.eclipse.ui.nav.model.TolerantXMLTokenizer.parseAttribute(TolerantXMLTokenizer.java:69)
    at de.pdark.decentxml.XMLTokenizer.next(XMLTokenizer.java:229)
    at de.pdark.decentxml.XMLParser.parseElement(XMLParser.java:769)
    at de.pdark.decentxml.XMLParser.parseElementContent(XMLParser.java:876)
    at de.pdark.decentxml.XMLParser.parseElement(XMLParser.java:821)
    at de.pdark.decentxml.XMLParser.parse(XMLParser.java:159)
    at org.apache.sling.ide.eclipse.ui.nav.model.TolerantXMLParser.parse(TolerantXMLParser.java:50)
    at org.apache.sling.ide.eclipse.ui.nav.model.TolerantXMLParser.parse(TolerantXMLParser.java:38)
    at org.apache.sling.ide.eclipse.ui.nav.model.TolerantXMLParser.parse(TolerantXMLParser.java:34)
    at org.apache.sling.ide.eclipse.ui.nav.model.GenericJcrRootFile.<init>(GenericJcrRootFile.java:57)
    at org.apache.sling.ide.eclipse.ui.nav.model.JcrNode.initChildren(JcrNode.java:376)
    at org.apache.sling.ide.eclipse.ui.nav.model.JcrNode.initChildren(JcrNode.java:411)
    at org.apache.sling.ide.eclipse.ui.nav.model.JcrNode.initChildren(JcrNode.java:411)
    at org.apache.sling.ide.eclipse.ui.nav.model.JcrNode.initChildren(JcrNode.java:411)
    at org.apache.sling.ide.eclipse.ui.nav.model.JcrNode.initChildren(JcrNode.java:411)
    at org.apache.sling.ide.eclipse.ui.nav.model.JcrNode.getChildren(JcrNode.java:352)
    at org.apache.sling.ide.eclipse.ui.nav.model.SyncDir.getNode(SyncDir.java:93)
    at org.apache.sling.ide.eclipse.ui.views.JcrPropertiesView.refreshContent(JcrPropertiesView.java:543)
    at org.apache.sling.ide.eclipse.ui.views.JcrPropertiesView$1.syncDirUpdated(JcrPropertiesView.java:148)
    at org.apache.sling.ide.eclipse.ui.nav.model.SyncDirManager.syncDirChanged(SyncDirManager.java:54)
    at org.apache.sling.ide.eclipse.ui.nav.model.SyncDirManager.registerNewSyncDir(SyncDirManager.java:44)
    at org.apache.sling.ide.eclipse.ui.nav.model.SyncDir.<init>(SyncDir.java:38)
    at org.apache.sling.ide.eclipse.ui.nav.JcrContentContentProvider.projectGetChildren(JcrContentContentProvider.java:129)
    at org.apache.sling.ide.eclipse.ui.nav.JcrContentContentProvider.getPipelinedChildren(JcrContentContentProvider.java:259)
    at org.eclipse.ui.internal.navigator.extensions.SafeDelegateTreeContentProvider.getPipelinedChildren(SafeDelegateTreeContentProvider.java:178)
    at org.eclipse.ui.internal.navigator.NavigatorContentServiceContentProvider.pipelineChildren(NavigatorContentServiceContentProvider.java:206)
    at org.eclipse.ui.internal.navigator.NavigatorContentServiceContentProvider.access$1(NavigatorContentServiceContentProvider.java:192)
    at org.eclipse.ui.internal.navigator.NavigatorContentServiceContentProvider$1.run(NavigatorContentServiceContentProvider.java:161)
    at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
    at org.eclipse.ui.internal.navigator.NavigatorContentServiceContentProvider.internalGetChildren(NavigatorContentServiceContentProvider.java:139)
    at org.eclipse.ui.internal.navigator.NavigatorContentServiceContentProvider.getChildren(NavigatorContentServiceContentProvider.java:125)
    at org.eclipse.jface.viewers.AbstractTreeViewer.getRawChildren(AbstractTreeViewer.java:1367)
    at org.eclipse.jface.viewers.TreeViewer.getRawChildren(TreeViewer.java:391)
    at org.eclipse.jface.viewers.StructuredViewer.getFilteredChildren(StructuredViewer.java:917)
    at org.eclipse.jface.viewers.AbstractTreeViewer.getSortedChildren(AbstractTreeViewer.java:620)
    at org.eclipse.jface.viewers.AbstractTreeViewer.updateChildren(AbstractTreeViewer.java:2643)
    at org.eclipse.jface.viewers.AbstractTreeViewer.internalRefreshStruct(AbstractTreeViewer.java:1923)
    at org.eclipse.jface.viewers.TreeViewer.internalRefreshStruct(TreeViewer.java:721)
    at org.eclipse.jface.viewers.AbstractTreeViewer.internalRefresh(AbstractTreeViewer.java:1898)
    at org.eclipse.jface.viewers.AbstractTreeViewer.internalRefresh(AbstractTreeViewer.java:1855)
    at org.eclipse.ui.navigator.CommonViewer.internalRefresh(CommonViewer.java:561)
    at org.eclipse.jface.viewers.StructuredViewer$8.run(StructuredViewer.java:1535)
    at org.eclipse.jface.viewers.StructuredViewer.preservingSelection(StructuredViewer.java:1443)
    at org.eclipse.jface.viewers.TreeViewer.preservingSelection(TreeViewer.java:403)
    at org.eclipse.jface.viewers.StructuredViewer.preservingSelection(StructuredViewer.java:1404)
    at org.eclipse.jface.viewers.StructuredViewer.refresh(StructuredViewer.java:1533)
    at org.eclipse.jface.viewers.ColumnViewer.refresh(ColumnViewer.java:555)
    at org.eclipse.ui.navigator.CommonViewer.refresh(CommonViewer.java:350)
    at org.eclipse.jdt.internal.ui.packageview.PackageExplorerContentProvider$3.run(PackageExplorerContentProvider.java:957)
    at org.eclipse.jdt.internal.ui.packageview.PackageExplorerContentProvider.runUpdates(PackageExplorerContentProvider.java:195)
    at org.eclipse.jdt.internal.ui.packageview.PackageExplorerContentProvider.runPendingUpdates(PackageExplorerContentProvider.java:187)
    at org.eclipse.jdt.internal.ui.packageview.PackageExplorerContentProvider$1.runInUIThread(PackageExplorerContentProvider.java:165)
    at org.eclipse.ui.progress.UIJob$1.run(UIJob.java:95)
    at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
    at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:135)
    at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4145)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3762)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$9.run(PartRenderingEngine.java:1113)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:997)
    at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:140)
    at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:611)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
    at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:567)
    at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
    at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:124)
    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:354)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:181)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:636)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:591)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1450)
    at org.eclipse.equinox.launcher.Main.main(Main.java:1426)

**Comment by rombert** [comment]
Thanks for the report, I'll have a look for the next release

**Comment by hanggao121** [comment]
thanks for reply.
There has strangely in my test.When I input word as "カレンダー",there has not error.
When I input other word such as "北海道",error was happened.

**Comment by rombert** [comment]
I can't get an error with any of the test words. Can you please upload a minimal test file that I can use to trigger the error myself?

**Comment by gabrielwalt** [comment]
Closing this as there hasn't been activity since over a year.
